# PERSISTENT VOLUME CLAIMS (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  resources:
    requests:
      storage: 200Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
