# PERSISTENT VOLUME CLAIMS (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claimss
spec:
  resources:
    requests:
      storage: 500Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
